spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: rahulkitt02@gmail.com
    password: socz iwad ncws rbem
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    net:
      digest:
        journalApp: INFO


Api:
  Key:
    weather: 154ab042e329ac8f28661fc6eb1659f8
    quotes: https://dummyjson.com/quotes/random